### ISSUE TITLE
URL Shortening

### ISSUE THREAD

**Issue by chetanmekha** [infobip/infobip-api-examples#1]
Hi Team, @mstipanov @gavocanov @lpandzic @tjuric 
I want to reduce the url link with infobip api and send that in sms. I gone through your documents but nothing was found relevant to this. Can you please share the request and response format for the same so that i can include within my application.
We are already having paid account for infobip services.

**Comment by lpandzic** [comment]
@ivan-letenko can you help?

**Comment by ivan-letenko** [comment]
Hello Chetan! We have a solution, but it is not in general availability, please contact our support team and we will provide you an example and more information, you can mention me (Ivan Letenko) as a contact person.

**Comment by chetanmekha** [comment]
ok will ask support team to connect with you

**Comment by chetanmekha** [comment]
@ivan-letenko we tried to call advance sms request but not getting success. Can you please help us like what is the issue. Its become shows topper for us.
`{
    "requestError": {
        "serviceException": {
            "messageId": "UNAUTHORIZED",
            "text": "Invalid login details"
        }
    }
}`

**Comment by ivan-letenko** [comment]
@chetanmekha Hi, what authorization method are you using? We suggest using the _API Key Header_, just remember to add the "App" api key prefix. 
e.g. `Authorization: App 003026bbc133714df1834b8638bb496e-8f4b3d9a-e931-478d-a994-28a725159ab9`
More information on API Authentication [here](https://www.infobip.com/docs/essentials/api-authentication)
